version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    working_directory: ~/repos
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler
      - run:
          name: install dependencies
          command: bundle install
      - run:
          name: run RuboCop
          command: bundle exec rubocop
      - run:
          name: update gem
          command: bundle exec rake bundle:update
      - run:
          name: check gem
          command: bundle exec rake bundle:check
      - run:
          name: run test
          command: bundle exec rake test
